background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    outer_color = rgb(585b70)
    inner_color = rgb(1e1e2e)
    font_color = rgb(cdd6f4)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 64
    font_family = JetBrains Mono
    color = rgb(cdd6f4)
    position = 0, 80
    halign = center
    valign = center
}
