#!/bin/sh

# clipboard manager using rofi
# requires rofi, cliphist and wl-clipboard to function

export PATH="$HOME/.nix-profile/bin:$PATH"
cliphist list | rofi -dmenu -p "Clipboard" | cliphist decode | wl-copy
